permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - "**/*.sh"
      - ".shellcheckrc"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/wildcard-shellcheck.yml"
jobs:
  wildcard:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
