permissions:
  contents: none
  pull-requests: none
on:
  push:
    branches:
      - wildcard
    paths:
      - "internal/**/*"
      - "*.go"
      - "go.*"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/wildcard-go.yml"
jobs:
  wildcard:
    runs-on: ubuntu-latest
    steps:
      - run: |
          true
